language: objective-c
osx_image: xcode8.2
before_install:
  - brew update
install:
  - ./travis/install-fastlane.sh
  - ./travis/install-mogenerator.sh
  - export PATH="$HOME/bin:$HOME/.fastlane/bin:$PATH"
script:
  - ./travis/run-tests.sh

