language: objective-c
osx_image: xcode8.2
before_install:
  - brew update
install:
  - ./travis/install-fastlane.sh
  - ./travis/install-mogenerator.sh
  - ./travis/install-appledoc.sh
  - export PATH="$HOME/bin:$HOME/.fastlane/bin:$PATH"
script:
# disable tests due to issue BRIDGE-1727
#  - ./travis/run-tests.sh
  - ./travis/build-docs.sh

# deploy docs on a tag
deploy:
  provider: s3
  access_key_id: AKIAI6OL6JAPHW5QJTLQ
  secret_access_key:
    secure: FN9DKqIZmYdxaOJNAQf0/R0I0IlcWMi8417Mz4XAATs92ZauHdeTrQKeeRtFT2i8LHHVzxy1KEqJt5Uo3pOvH+Awn6TTuJBR+3aOrKh88L3Qcxcl2NFdbamR2xeBkSAUfGaiLTYEQuB+QbWlVKqilGvD2wAQc37+pUv207prgJg=
  bucket: developer.sagebridge.org
  skip_cleanup: true
  local_dir: Documentation
  upload-dir: "$TRAVIS_XCODE_PROJECT/$TRAVIS_TAG"
  on:
    tags: true
